apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: ${AIRFLOW_NAMESPACE}
spec:
  type: NodePort
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432
      nodePort: ${POSTGRES_EXTERNAL_PORT}
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql