MLFLOW_ENDPOINT = 'http://mlflow:5000'
MLFLOW_EXPERIMENT = 'survival_analysis'

# METRIC FOR BEST MODEL
METRIC_BM = "Validation_concordance_index_ipcw"
METRIC_BM_TYPE = "max"

# IDS TRUE CONNECTOR INFORMATION
TRUE_CONNECTOR_EDGE_IP = "XXX.XX.XXX.XX"        
TRUE_CONNECTOR_EDGE_PORT = "8889"
TRUE_CONNECTOR_CLOUD_IP = "XXX.XX.XXX.XX"
TRUE_CONNECTOR_CLOUD_PORT = "8084"
