apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  namespace: ${MINIO_NAMESPACE}
spec:
  type: NodePort
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: ${MINIO_EXTERNAL_PORT_API}
      protocol: TCP
    - name: ui
      port: 9001
      targetPort: 9001
      nodePort: ${MINIO_EXTERNAL_PORT_UI}
      protocol: TCP
  selector:
    app.kubernetes.io/name: minio